name: Test deployment

on:
  pull_request:
    branches:
      - main
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on
env:
  ALGOLIA_APP_ID: ${{ vars.ALGOLIA_APP_ID }}
  ALGOLIA_API_KEY: ${{ vars.ALGOLIA_API_KEY }}
  BAL_ADMIN_API_URL: ${{ vars.BAL_ADMIN_API_URL }}
  BAL_WIDGET_URL: ${{ vars.BAL_WIDGET_URL }}

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 22.8
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Test build website
        run: yarn build
